### ISSUE TITLE
Milestone 1 Report - List and Evaluation of Deliverables

### ISSUE THREAD

**Issue by irmakguzey** [bounswe/bounswe2019group6#148]
- [x] Project Plan
- [x] Authentication Endpoint
- [x] User Follow Endpoint
- [x] User Profile Endpoint
- [x] Authentication Interface in Android
- [x] User Profile Page in Android
- [x] Home Page in Android 
- [x] Authentication Interface in Web Frontend
- [x] User Profile Page in Web Frontend
- [x] Home Page in Web Frontend

**Comment by barandenizkorkmaz** [comment]
The preparation of the list&status and evaluation of deliverables sections have been completed.
